version: "3"

services:
  02-book-admin-mysql:
    container_name: 02-book-admin-mysql
    image: mysql:8.0
    environment:
      TZ: Asia/Tokyo
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    env_file:
      - .env
    networks:
      app_net:
        ipv4_address: '172.30.0.2'

  02-book-admin-app:
    container_name: 02-book-admin-app
    build: ./book_admin/
    image: 02-book-admin-app
    command: bundle exec rails server -b 0.0.0.0
    tty: true
    stdin_open: true
    volumes:
      - ./book_admin:/app:cached
      - bundle_data:/usr/local/bundle:cached
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
    env_file:
      - .env
    depends_on:
      - 02-book-admin-mysql
    ports:
      - 4000:3000 # ポートフォワード
    networks:
      app_net:
        ipv4_address: '172.30.0.3'

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

volumes:
  mysql_data:
  bundle_data:
  node_modules: